version: 2.0

aliases:
  - &ci-build-image quay.io/yeebase/ci-build:7.2
  
  - &save_composer_cache
    key: composer-cache-v1-{{ .Branch }}-{{ checksum "composer.json" }}
    paths:
      - /composer/cache-dir

  - &restore_composer_cache
    keys:
      - composer-cache-v1-{{ .Branch }}-{{ checksum "composer.json" }}
      - composer-cache-v1-{{ .Branch }}-
      - composer-cache-v1-

jobs:
  test:
    docker:
      - image: *ci-build-image
    environment:
      COMPOSER_CACHE_DIR: /composer/cache-dir
    steps:
      - checkout
      - restore_cache: *restore_composer_cache
      
      - run: composer update
      - run: vendor/bin/phpunit
      - run: vendor/bin/phpcs
      - run: vendor/bin/phpstan analyse --ansi
      
      - save_cache: *save_composer_cache

workflows:
  version: 2
  build_and_test:
    jobs:
      - test